require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - lib/templates/**/*
    - vendor/**/*
    - tmp/**/*
    - public/**/*
    - node_modules/**/*

Rails/InverseOf:
  Enabled: false

Rails/Present:
  UnlessBlank: false

Rails/Blank:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

Style/StringLiterals:
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true

Metrics/LineLength:
  Description: 'Limit lines to 200 characters.'
  Max: 200

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/Focus:
  Enabled: false
